config/routes.rb
Rails.application.routes.draw do
  get 'boards', :to => 'materials#boards'
  get 'edges', :to => 'materials#edges'
  get 'fittings', :to => 'materials#fittings'
  get 'specials', :to => 'materials#specials'
  get 'varnish', :to => 'materials#varnish'
  get 'veneer', :to => 'materials#veneer'
  get 'wood', :to => 'materials#wood'
  get 'surface', :to => 'materials#surface'
  get 'wall', :to => 'materials#wall'
  get 'floor', :to => 'materials#floor'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/material_concern.rb
require "uri"
require "net/http"
module MaterialConcern
  extend ActiveSupport::Concern

  def request_data(url)
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)
    request["accept"] = "text/plain"
    request["Authorization"] = "Bearer FDDBB275CCB42F7475D36DBEABD98645F61F625CB31ED28A03F34D80AAF71C6D"
    request["Cookie"] = ".AspNetCore.LocalAccessTokenValidation=CfDJ8K7yQcQ9kB9Okz_e40tXwKkBPre1pVAYebDPhN3ZPxAC24FBObVq44KsylZR1FFfyytns9xuApOlpSlrtPcC80qRugpJHK8CZ9cfT1ur1KZ6bWyEuaJaZFoB1132VY5qNEaGJC_7SlgEZB0cjdbP0tWI-bbPlod4YVeU1BNDrAUuU8nwThN3v0KM-xpq3d33mcXZxYOP-l-HNIWtgSP5-O9MXoDhto1OrCJdb_Cy_DH7YOS-i4jVcZiJ-fNo96olACRKy5M-bQ4mS_7gr2tST7gmlD79thq4-AOAyEWLg8PrQ8D3GU4rNC4DxHSxP3DBXS3bhqd3Qd_w-bFCB1VvEMtBtOBIzxyyHM55D0CidRjQ0h2UHFbdozNvAEAbGpRnAcplg3ePUVPDa7Lx_Oz-3sqCJBKDF1tXfDgXGoRF9iY9WCgdLB2K0nZvWleZTEfy06zsi1xFi_CZG8yGaCliCyY2sApxZMr1_VO6bQgoEZlVR2G8OmaBEYibYXjUq7XQn-mjEQAzysDKrHpKuvE7Wxi36JciuNyBXctHF90tW3FoKkeIcc--uQNnLRX1vByOmvQOL3enFSqw956xDiN2WFzQmbaA25akWH6go20SI5Eua1ACi-ci7MiyDw7M_I30M45Rrvi7YL_-Jbk5lJAu4qKbV_EU5-QMXNpP4QTP9Qv0OWoB-qwpcs9CpM7iFzSIaNOPhcn4Pck5C7LvP3VDF_yI1weF572DhdeJZf3qR1Lkoa5qzjZkoJWjHndTsUdOc0LoNr0dmu5IYvAgEcJ0fJMFrsqlko4c8tf943oslpU-tPvBB-t2T6XDSaZMub8MIKtzwSqEm4Cvb1TCLvTGX9s2iPaib2Bfx6KLsp20p4ZY_Rrk7MF25VFscYO1aY56_0fodQk13mWFsLbfP1-9rGaQdYOwPFHgD8Rhgsk9t_YVeESSBPp8TJEzZH_cO2zsOg"

    response = https.request(request)
    JSON.parse(response.body)["data"]
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  include MaterialConcern

  def boards
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/board")
    @parsed = request_data(url)
    # render :json => render_to_string(:action => 'index', :layout => false)
  end

  def edges
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/edge")
    @parsed = request_data(url)
  end

  def fittings
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/fitting")
    @parsed = request_data(url)
  end

  def specials
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/special")
    @parsed = request_data(url)
  end

  def varnish
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/varnish")
    @parsed = request_data(url)
  end

  def veneer
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/veneer")
    @parsed = request_data(url)
  end

  def wood
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/wood")
    @parsed = request_data(url)
  end

  def surface
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/surface")
    @parsed = request_data(url)
  end

  def wall
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/wall")
    @parsed = request_data(url)
  end

  def floor
    url = URI("https://sales.cadt365.com/api/masterData/material/viewGroup/floor")
    @parsed = request_data(url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/edge_helper.rb
module EdgeHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Materials</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= yield %>
</body>
</html>

<script>
    function openNav(h_id, img_name, density, path, img_src, clr_id) {
        const image = document.getElementById("img_id")
        image.innerText = h_id
        const name = document.getElementById("img_name")
        name.innerText = img_name
        const den = document.getElementById("density")
        den.innerText = density
        // alert(clr_id)
        const clr = document.getElementById("clr_id")
        clr.innerText = clr_id
        document.getElementById("thumbnail_image").src = `${img_src}`
        document.getElementById("mySidebar").style.width = "278px";
    }

    function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
    }
</script>

app/views/materials/_link.html.erb
<div class="affix">
  <%= link_to "Boards", boards_path %>
  <%= link_to "Edges", edges_path %>
  <%= link_to "Fittings", fittings_path %>
  <%= link_to "Specials", specials_path %>
  <%= link_to "Varnish", varnish_path %>
  <%= link_to "veneer", veneer_path %>
  <%= link_to "wood", wood_path %>
  <%= link_to "surface", surface_path %>
  <%= link_to "wall", wall_path %>
  <%= link_to "floor", floor_path %>
</div>

app/views/materials/_middle_data.html.erb
<div class="material-item">
  <div class="color-conatiner">
    <% count = 0 %>
    <% @parsed.each do |h| %>
      <% count += 1 %>
      <div class="color-item" onclick="openNav('<%=h['id'] %>','<%= h['name']['en']%>','<%= h['density'] %>','<%= h['thumbnailPath'] %>', '/assets/<%= count % 7 + 1%>.jpg', '<%= h['thickness'] %>')">
        <img src="/assets/<%= count % 7 + 1 %>.jpg">
        <h2><%= h['name']['en'] %></h2>
      </div>
    <% end %>
  </div>
</div>
<div class="material-item">
  <div id="mySidebar" class="sidebar">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
    <div id="inner_sidebar" style="padding: 20px;color: black;font-size: larger;font-family: fantasy;">
      <img id="thumbnail_image" style="width: 200px; height: 180px; display: block; margin: 0 auto;" src=""/>
      <p id="img_id"></p>
      <p id="img_name"></p>
      <p id="density"></p>
      <p id="clr_id"></p>
    </div>
  </div>
</div>

app/views/materials/_nav.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: aliceblue; margin-bottom: 0">
  <div class="navbar-brand" href="#" style="color: antiquewhite; display: flex; padding: 8px; width: 100%">
    <p style="margin-top: 4px; width: 216px; color: cadetblue;margin-left: 30px; font-weight: 700">EOS Design
      Cloud</p>
<!--    <form class="form-inline">-->
<!--      <input class="form-control mr-sm-2" type="search..." placeholder="Search" aria-label="Search">-->
<!--    </form>-->
    <div style="margin-left: auto;margin-right: 0;margin-left: auto; margin-right: 0; color: black;width: 180px;margin-top: 8px; color: cadetblue; display: flex; justify-content: space-between;">
      <input type="range" class="form-range" id="#" style="display: initial;width: 90px; accent-color: currentcolor; margin-bottom: 5px">
      <i class="fa-solid fa-arrow-rotate-right"></i>
      <i class="fa-solid fa-pencil"></i>
    </div>
  </div>
</nav>

app/views/materials/boards.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/edges.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/fittings.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/floor.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/specials.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item"style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/surface.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item"style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/varnish.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item"style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/veneer.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/wall.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>

app/views/materials/wood.html.erb
<div class="material-wrapper">
  <div class="material-container">
    <%= render partial: 'nav' %>
    <div class="materials-item-con">
      <div class="material-item" style="background-color: aliceblue">
        <%= render partial: 'link' %>
      </div>
      <%= render partial: 'middle_data' %>
    </div>
  </div>
</div>